name: Java CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 16
    - uses: actions/checkout@v2.3.3
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Create staging directory
      run: mkdir staging
    - name: Copy JAR to staging directory
      run: cp target/*.jar staging/
